language: node_js
node_js: "11"
cache:
  yarn: true
  directories:
    - node_modules
script: 
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  verbose: true
  on:
    branch: master